# Generated by Django 2.2.12 on 2020-05-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_hgfghfh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hgfghfh',
        ),
    ]
